# Generated by Django 5.1.4 on 2025-01-15 15:57

import books.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=books.models.TimestampWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='deleted_at',
            field=books.models.TimestampWithoutTZField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=books.models.TimestampWithoutTZField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=books.models.TimestampWithoutTZField(auto_now=True),
        ),
    ]
