# Generated by Django 5.1.4 on 2025-04-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_created_at_alter_book_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='books.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('id', 'Indonesian'), ('en', 'English')], default='id', max_length=2),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
