# Generated by Django 5.1.4 on 2025-07-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_must_read',
            field=models.BooleanField(default=False),
        ),
    ]
