# Generated by Django 5.1.4 on 2025-01-15 15:57

import borrow_records.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecords',
            name='borrow_date',
            field=borrow_records.models.TimestampWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowrecords',
            name='created_at',
            field=borrow_records.models.TimestampWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowrecords',
            name='deleted_at',
            field=borrow_records.models.TimestampWithoutTZField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecords',
            name='due_date',
            field=borrow_records.models.TimestampWithoutTZField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecords',
            name='return_date',
            field=borrow_records.models.TimestampWithoutTZField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecords',
            name='updated_at',
            field=borrow_records.models.TimestampWithoutTZField(auto_now=True),
        ),
    ]
